version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 2
      semver-major-days: 7
      semver-minor-days: 2
      semver-patch-days: 2
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/examples/visualization"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 2
      semver-major-days: 7
      semver-minor-days: 2
      semver-patch-days: 2
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
